# version: '3.8'
# services:
#   postgres:
#     image: postgres
#     ports:
#       - "5432"
#     environment:
#       POSTGRES_DB: prisma
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123123
#     volumes:
#       - "./tmp/postgres:/var/lib/postgresql/data"